FROM docker.io/library/tomcat:9.0.105-jdk11    

MAINTAINER "MINJUNG<wndtmgld5551@gmail.com>"

RUN rm -rf /usr/local/tomcat/webapps/

ADD target/ohgoodfood-1.0.0-BUILD-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
